-- Exactly-Once Semantics Migration (Phase 16 - PostgreSQL)
-- Adds tables for idempotent producers, transactions, and LSO tracking.

-- ============================================================================
-- PRODUCER STATE (Idempotent Producers)
-- ============================================================================

-- Registered producers (for ID assignment and epoch tracking)
CREATE TABLE IF NOT EXISTS producers (
    id TEXT PRIMARY KEY,                    -- UUID generated by client or server
    organization_id TEXT,                   -- Optional: for multi-tenant isolation
    transactional_id TEXT,                  -- Optional: for transactional producers
    epoch INTEGER NOT NULL DEFAULT 0,       -- Incremented on producer restart (fencing)
    created_at BIGINT NOT NULL,
    last_heartbeat BIGINT NOT NULL,
    state TEXT NOT NULL DEFAULT 'active',   -- 'active', 'fenced', 'expired'
    metadata TEXT                           -- JSON metadata (client info, etc.)
);

-- Unique constraint for transactional_id per organization
CREATE UNIQUE INDEX IF NOT EXISTS idx_producers_org_txn
ON producers(organization_id, transactional_id)
WHERE transactional_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_producers_org ON producers(organization_id);
CREATE INDEX IF NOT EXISTS idx_producers_transactional ON producers(transactional_id);
CREATE INDEX IF NOT EXISTS idx_producers_state ON producers(state);

-- Producer sequence tracking (for deduplication)
-- Stores the last sequence number seen for each producer/topic/partition combo
CREATE TABLE IF NOT EXISTS producer_sequences (
    producer_id TEXT NOT NULL REFERENCES producers(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    partition_id INTEGER NOT NULL,
    last_sequence BIGINT NOT NULL DEFAULT -1,  -- -1 means no records yet
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (producer_id, topic, partition_id)
);

CREATE INDEX IF NOT EXISTS idx_producer_seq_topic ON producer_sequences(topic, partition_id);

-- ============================================================================
-- TRANSACTIONS (Transactional Writes)
-- ============================================================================

-- Active and recent transactions
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id TEXT PRIMARY KEY,        -- UUID
    producer_id TEXT NOT NULL REFERENCES producers(id) ON DELETE CASCADE,
    state TEXT NOT NULL DEFAULT 'ongoing',  -- 'ongoing', 'preparing', 'committed', 'aborted'
    timeout_ms INTEGER NOT NULL DEFAULT 60000,
    started_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    completed_at BIGINT
);

CREATE INDEX IF NOT EXISTS idx_transactions_producer ON transactions(producer_id);
CREATE INDEX IF NOT EXISTS idx_transactions_state ON transactions(state);
CREATE INDEX IF NOT EXISTS idx_transactions_completed ON transactions(completed_at) WHERE completed_at IS NOT NULL;

-- Transaction partition tracking (which partitions are part of transaction)
CREATE TABLE IF NOT EXISTS transaction_partitions (
    transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    partition_id INTEGER NOT NULL,
    first_offset BIGINT NOT NULL,           -- First offset written in this txn
    last_offset BIGINT NOT NULL,            -- Last offset written (updated as records added)
    PRIMARY KEY (transaction_id, topic, partition_id)
);

CREATE INDEX IF NOT EXISTS idx_txn_partitions_topic ON transaction_partitions(topic, partition_id);

-- Transaction markers (written to segments to indicate commit/abort boundaries)
CREATE TABLE IF NOT EXISTS transaction_markers (
    id TEXT PRIMARY KEY,
    transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    partition_id INTEGER NOT NULL,
    "offset" BIGINT NOT NULL,               -- Offset of the marker record
    marker_type TEXT NOT NULL,              -- 'commit' or 'abort'
    created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_txn_markers_partition ON transaction_markers(topic, partition_id, "offset");

-- ============================================================================
-- CONSUMER OFFSETS (Enhanced for Read-Committed)
-- ============================================================================

-- Consumer group configuration for isolation level
CREATE TABLE IF NOT EXISTS consumer_group_config (
    group_id TEXT PRIMARY KEY,
    isolation_level TEXT NOT NULL DEFAULT 'read_uncommitted',  -- 'read_uncommitted' or 'read_committed'
    enable_auto_commit BOOLEAN NOT NULL DEFAULT true,
    auto_commit_interval_ms INTEGER NOT NULL DEFAULT 5000,
    session_timeout_ms INTEGER NOT NULL DEFAULT 30000,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- Last Stable Offset (LSO) tracking per partition
-- LSO = highest offset where all transactions below are committed/aborted
CREATE TABLE IF NOT EXISTS partition_lso (
    topic TEXT NOT NULL,
    partition_id INTEGER NOT NULL,
    last_stable_offset BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (topic, partition_id)
);

CREATE INDEX IF NOT EXISTS idx_partition_lso_topic ON partition_lso(topic);
